In [6]:
import os
os.chdir(r'D:\새 폴더\Programing\Academy\Python\day0825')


In [ ]:
score=[[100,80,80],[50,60,100]]

print(score)
print(score[1][0:2])
score[1][0:2]=0 # list는 한번에 여러개 수정이 불가, 슬라이스 사용불가
print(score)



[[100, 80, 80], [50, 60, 100]]
[50, 60]


TypeError: must assign iterable to extended slice

In [14]:
import numpy as np

score=[[100,80,80],[50,60,100]]
s_arr=np.array(score)

print(s_arr)

[[100  80  80]
 [ 50  60 100]]


In [ ]:
d= np.array([2,3,4,5,6])
print(d,type(d))
print(d.dtype)
print(d.shape) # 튜플타입으로 반환
# 배열의 모든 요소의 타입은 일치함

d2= np.array([[1,2,3,4,5],[2,3,4,5,6.0]])
print(d2,type(d2))
print(d2.dtype)
print(d2.shape)


[2 3 4 5 6] <class 'numpy.ndarray'>
int64
(5,)
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]] <class 'numpy.ndarray'>
float64
(2, 5)


In [28]:
# 문자열 배열
arr=np.array(['apple','banana','cherry'])
print(arr, arr.dtype) # <U6 : 최대 길이 6의 유니코드 문자열
print(arr.shape)

# boolean 배열
arr= np.array([True,False,True])
print(arr, arr.dtype)

# 객체 배열 == list
arr= np.array([1,'hello',[1,2,3],True] ,dtype=object) # 요소들을 object 타입으로 통일
print(arr, arr.dtype)

# 숫자 배열 -> 계산 최적화(가장 효율적)
# 문자열 배열, boolean 배열도 가능하지만 수학 계산에는 부적합

['apple' 'banana' 'cherry'] <U6
(3,)
[ True False  True] bool
[1 'hello' list([1, 2, 3]) True] object


In [ ]:
data=np.arange(1,5)
print(data, data.dtype)
data=data.astype('float64') # 그냥 float만 써도 되긴하네
print(data, data.dtype)
data=data.astype('int32')
print(data, data.dtype)


[1 2 3 4] int64
[1. 2. 3. 4.] float64
[1 2 3 4] int64


In [24]:
d1=np.zeros((2,5))
print(d1)
d2=np.ones((3,4))
print(d2)
d3=np.arange(1,6)
print(d3)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4 5]


In [31]:
d4= np.random.randn(1,5) # 정규분포( 중앙값 0, 표준편차 1)에서 난수 10개를 뽑아 배열생성
print(d4)

[[ 1.09068234 -0.23068582 -0.72158703 -0.67378846 -1.26653709]]


In [32]:
a=np.ones((2,3))
print(a)
b=np.transpose(a)
print(b,b.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]] (3, 2)


In [29]:
arr1=np.array([[2,3,4],[6,7,8]])
arr2=np.array([[12,23,34],[36,47,58]])

# 배열의 덧셈
print(arr1+arr2)
# 배열의 곱셈
print(arr1*arr2)
# 배열의 나눗셈
print(arr1/arr2)
# 배열의 뺄셈
print(arr1-arr2)

[[14 26 38]
 [42 54 66]]
[[ 24  69 136]
 [216 329 464]]
[[0.16666667 0.13043478 0.11764706]
 [0.16666667 0.14893617 0.13793103]]
[[-10 -20 -30]
 [-30 -40 -50]]


In [ ]:
arr3= np.array([100,200,300])
# 크기가 다를 경우
print(arr1+arr3)
print(arr3+arr1)

arr4=np.array([100,200,300,400,500])
print(arr1+arr4) # 행이나 열의 크기 중 하나는 같아야함

[[102 203 304]
 [106 207 308]]
[[102 203 304]
 [106 207 308]]


ValueError: operands could not be broadcast together with shapes (2,3) (5,) 

In [19]:
import numpy as np
import module.usecsv as usecsv

quest=np.array(usecsv.switch(usecsv.opencsv('quest.csv')))
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [14]:
print(quest>5)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False  True False False]
 [False  True False False False]
 [False False False False  True]
 [False False False False False]]


In [18]:
quest[quest>5]=5
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 5. 2. 5.]
 [3. 5. 4. 2. 5.]
 [3. 5. 4. 1. 5.]
 [3. 5. 5. 1. 3.]]


In [27]:
d=np.all((quest>=0) & (quest<6), axis=1) 
print(d)

q_d=quest[d]
print(q_d)

[ True  True  True  True False False False  True]
[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [3. 5. 5. 1. 3.]]


In [24]:
# matrix_a = [[1,1,2],[2,1,1]]
# matrix_b = [[1,1],[2,1],[1,3]]

# result = [[sum(a*b for a , b in zip(row_a, column_b))
#                   for column_b in zip(*matrix_b)] for row_a in matrix_a]
# print(result)


matrix_a=np.array([[1,1,2],[2,1,1]])
matrix_b=np.array([[1,1],[2,1],[1,3]])

result= matrix_a @ matrix_b # 행렬의 곱
print(result)


[[5 8]
 [5 6]]


In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

total = np.sum(arr)         # 모든 요소 합
col_sum = np.sum(arr, axis=0)  # 열 합
row_sum = np.sum(arr, axis=1)  # 행 합

print(total)    # 21
print(col_sum)  # [5 7 9]
print(row_sum)  # [ 6 15]

21
[5 7 9]
[ 6 15]


In [29]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

total_mean = np.mean(arr)          # 전체 평균
col_mean = np.mean(arr, axis=0)    # 열 평균
row_mean = np.mean(arr, axis=1)    # 행 평균

print(total_mean)  # 3.5
print(col_mean)    # [2.5 3.5 4.5]
print(row_mean)    # [2. 5.]

3.5
[2.5 3.5 4.5]
[2. 5.]


문제1 :
1부터 10까지의 정수로 이루어진 NumPy 배열을 만들고,

배열의 합, 배열의 평균, 배열의 제곱 각각 출력


문제2:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


두 번째 행만 출력
첫 번째 열만 출력
(2,2) 위치의 원소를 출력


문제3 :
다음 두 행렬의 곱(np.dot)
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])


문제4:
다음 배열에 10을 더하기.(반복문 없이 NumPy 연산 사용)
arr = np.array([1, 2, 3, 4, 5])


문제5:
다음 배열의
arr = np.array([10, 20, 30, 40, 50])
최댓값(max()), 최솟값(min()), 표준편차(stu()) 출력

In [79]:
# 문제1 :
# 1부터 10까지의 정수로 이루어진 NumPy 배열을 만들고, 배열의 합, 배열의 평균, 배열의 제곱 각각 출력
import numpy as np

Numpy=np.arange(1,11)
num_sum=np.sum(Numpy)
num_mean=np.mean(Numpy)
# num_pow=np.pow(Numpy,2)
num_pow=Numpy ** 2


print(f'합:{num_sum}\n평균:{num_mean}\n제곱:{num_pow}\n ')

합:55
평균:5.5
제곱:[  1   4   9  16  25  36  49  64  81 100]
 


In [85]:
# 문제2:

# 두 번째 행만 출력
# 첫 번째 열만 출력
# (2,2) 위치의 원소를 출력

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[1])
print(arr[:,0])
print(arr[1][1])

[4 5 6]
[1 4 7]
5


In [72]:
# 문제3 :
# 다음 두 행렬의 곱(np.dot)
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A,B))

print(A@B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [63]:
# 문제4:
# 다음 배열에 10을 더하기.(반복문 없이 NumPy 연산 사용)
arr = np.array([1, 2, 3, 4, 5])

arr=arr+10

print(arr)


[11 12 13 14 15]


In [75]:
# 문제5:
# 다음 배열의 최댓값(max()), 최솟값(min()), 표준편차(std()) 출력
arr = np.array([10, 20, 30, 40, 50])

print(np.max(arr))
print(np.min(arr))
print(np.std(arr))


50
10
14.142135623730951
