In [ ]:
import os
os.chdir(r'D:\새 폴더\Programing\Academy\Python\day0826')


In [36]:
import numpy as np
a = np.random.randint(1, 11, [2, 3])
b = np.random.randint(1, 11, [2, 3])
# -> 1~10까지의 변수로 [2,3] 배열 생성

print(a)
print(b)

# greater, greater_equal, equal, not_equal, less, less_equal
j = np.less_equal(a, b)
print(j)
print("-----")

# maximum
k = np.maximum(a, b)  # 같은 인덱스의 값끼리 비교, 큰것만 출력
print(k)
print("-----")

# minimum
k = np.minimum(a, b)  # 같은 인덱스의 값끼리 비교, 작은 것만 출력
print(k)
print("-----")


name = np.array(["홍길동", "김길동", "이길동"])
kor = np.array([100, 90, 60])
eng = np.array([10, 60, 80])
mat = np.array([50, 40, 100])

# 평균60 넘는 학생이름
print(name[np.greater(np.divide(np.add(np.add(kor, eng), mat), 3), 60)])
# print(name[np.greater((kor+eng+mat)/3, 60)])

scores=np.array([kor,eng,mat]) # (3,3) 배열
print(scores)
# axios=1 : 행 방향(가로축)
# axios=0 : 열 방향(세로축) 

avg=scores.mean(axis=1)
print(avg>60)
print(name[avg>60])


[[9 1 8]
 [2 5 3]]
[[8 1 4]
 [7 1 5]]
[[False  True False]
 [ True False  True]]
-----
[[9 1 8]
 [7 5 5]]
-----
[[8 1 4]
 [2 1 3]]
-----
['김길동' '이길동']
['김길동' '이길동']
[[100  90  60]
 [ 10  60  80]
 [ 50  40 100]]
[ True False  True]
['홍길동' '이길동']
